In [1]:
import pandas as pd
import json
import ast


filename = "housing_data.csv"

In [2]:
col_list = ["AdditionalFields"]

df = pd.read_csv(filename, usecols=col_list)

k = 0

for i, j in df.iterrows():

    if i == 0:
        a_json = json.loads(j["AdditionalFields"])

        data = ast.literal_eval(a_json)
        a = list(data.items())

        additional_df = pd.DataFrame(a)
        additional_df = additional_df.T

    else:

        a_json = json.loads(j["AdditionalFields"])
        data = ast.literal_eval(a_json)
        a = list(data.values())
        new_row = pd.DataFrame(a).T
        additional_df = additional_df.append(new_row)

    k = k + 1

In [3]:
new_header = additional_df.iloc[0] 
additional_df = additional_df[1:] 
additional_df.columns = new_header

In [4]:
additional_df = additional_df.filter(['sold_price', 'sqarefootage','Type','Style','Bedrooms','Bathrooms','Kitchens', 'Rooms', 'Groceries #1 distance',
 'Groceries #2 distance',
 'Groceries #3 distance', 'Restaurants #1 distance',
 'Restaurants #2 distance',
 'Restaurants #3 distance','Coffee #1 distance',
 'Coffee #2 distance',
 'Coffee #3 distance','Gas Station #1 distance',
 'Gas Station #2 distance',
 'Gas Station #3 distance','Medical Care #1 distance',
 'Medical Care #2 distance',
 'Medical Care #3 distance','Park #1 distance',
 'Park #2 distance',
 'Park #3 distance','Library #1 distance',
 'Library #2 distance',
 'Library #3 distance','Pharmacy #1 distance',
 'Pharmacy #2 distance',
 'Pharmacy #3 distance','Mall #1 distance',
 'Mall #2 distance',
 'Mall #3 distance'])

additional_df

,sold_price,sqarefootage,Type,Style,Bedrooms,Bathrooms,Kitchens,Rooms,Groceries #1 distance,Groceries #2 distance,...,Park #3 distance,Library #1 distance,Library #2 distance,Library #3 distance,Pharmacy #1 distance,Pharmacy #2 distance,Pharmacy #3 distance,Mall #1 distance,Mall #2 distance,Mall #3 distance
1,"526,800",500-599,Condo Apt,Apartment,1,1,1,4,0.44,0.6,...,1.31,1.21,1.26,1.26,0.14,0.39,1.17,1.22,1.46,2
0,"1,805,000",n/a,Detached,Backsplit 4,3,2,1,8,0.73,0.81,...,1.03,2.5,2.56,2.56,0.73,1.26,1.39,1.36,1.79,1.79
0,"1,300,000",n/a,Semi-Detached,2-Storey,3,2,1,6,0.66,0.68,...,0.69,1.05,1.06,1.26,0.43,0.44,1.54,0.63,0.73,2.82
0,"1,250,000",n/a,Semi-Detached,2-Storey,3,2,1,7,0.74,1.07,...,3.18,0.6,0.6,0.6,0.29,1.97,2.68,3.33,5.09,4.63
0,"2,025,000",n/a,Detached,3-Storey,4,4,1,10,0.81,1.03,...,1.73,0.78,0.78,1.19,1.99,1.86,1.9,2.49,2.7,2.49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,"965,500",700-1100,Detached,Bungalow,2,2,1,5,1.29,1.82,...,1.23,0.4,0.41,1.89,0.53,1.55,1.78,1.75,1.95,4.47
0,"594,000",900-999,Condo Apt,Apartment,2,2,1,5,0.31,0.95,...,2.85,0.42,0.42,2.2,0.46,1.59,1.59,2.36,2.96,3.02
0,"471,000",1200-1399,Condo Townhouse,2-Storey,3,2,1,8,0.84,1.55,...,1.23,0.77,1.61,1.62,1.18,1.74,2.09,1.3,1.48,2.21
0,"770,000",900-999,Condo Townhouse,Apartment,2,2,1,6,0.42,0.89,...,1.34,1.44,1.42,1.42,0.87,1.45,1.45,0.7,1.37,1.9
0,"839,900",700-799,Condo Apt,Apartment,2,2,1,5,0.51,1.24,...,1.34,2.17,2.18,2.38,2.18,2.21,3.86,2.04,2.07,2.11

In [5]:
ar = ['Groceries #1 distance',
 'Groceries #2 distance',
 'Groceries #3 distance', 'Restaurants #1 distance',
 'Restaurants #2 distance',
 'Restaurants #3 distance','Coffee #1 distance',
 'Coffee #2 distance',
 'Coffee #3 distance','Gas Station #1 distance',
 'Gas Station #2 distance',
 'Gas Station #3 distance','Medical Care #1 distance',
 'Medical Care #2 distance',
 'Medical Care #3 distance','Park #1 distance',
 'Park #2 distance',
 'Park #3 distance','Library #1 distance',
 'Library #2 distance',
 'Library #3 distance','Pharmacy #1 distance',
 'Pharmacy #2 distance',
 'Pharmacy #3 distance','Mall #1 distance',
 'Mall #2 distance',
 'Mall #3 distance']
# len(X)
for field in ar:
    additional_df = additional_df[additional_df[field] != "km"]
    

additional_df = additional_df[additional_df["sqarefootage"] != "n/a"]

In [6]:
X = additional_df.drop(['sold_price'],axis=1)
Y = additional_df.filter(['sold_price'])

In [7]:
# new_header = additional_df.iloc[0] 
# additional_df = additional_df[1:] 
# additional_df.columns = new_header 

# additional_df = additional_df.filter(['sold_price', 'sqarefootage','Type','Style','Bedrooms','Bathrooms','Kitchens', 'Rooms', 'Groceries #1 distance',
#  'Groceries #2 distance',
#  'Groceries #3 distance', 'Restaurants #1 distance',
#  'Restaurants #2 distance',
#  'Restaurants #3 distance','Coffee #1 distance',
#  'Coffee #2 distance',
#  'Coffee #3 distance','Gas Station #1 distance',
#  'Gas Station #2 distance',
#  'Gas Station #3 distance','Medical Care #1 distance',
#  'Medical Care #2 distance',
#  'Medical Care #3 distance','Park #1 distance',
#  'Park #2 distance',
#  'Park #3 distance','Library #1 distance',
#  'Library #2 distance',
#  'Library #3 distance','Pharmacy #1 distance',
#  'Pharmacy #2 distance',
#  'Pharmacy #3 distance','Mall #1 distance',
#  'Mall #2 distance',
#  'Mall #3 distance'])

# additional_df
# # list(additional_df)



# # len(X)
# ar = ['Groceries #1 distance',
#  'Groceries #2 distance',
#  'Groceries #3 distance', 'Restaurants #1 distance',
#  'Restaurants #2 distance',
#  'Restaurants #3 distance','Coffee #1 distance',
#  'Coffee #2 distance',
#  'Coffee #3 distance','Gas Station #1 distance',
#  'Gas Station #2 distance',
#  'Gas Station #3 distance','Medical Care #1 distance',
#  'Medical Care #2 distance',
#  'Medical Care #3 distance','Park #1 distance',
#  'Park #2 distance',
#  'Park #3 distance','Library #1 distance',
#  'Library #2 distance',
#  'Library #3 distance','Pharmacy #1 distance',
#  'Pharmacy #2 distance',
#  'Pharmacy #3 distance','Mall #1 distance',
#  'Mall #2 distance',
#  'Mall #3 distance']
# # len(X)
# for field in ar:
#     additional_df = additional_df[additional_df[field] != "km"]



# X = additional_df.drop(['sold_price'],axis=1)
# Y = additional_df.filter(['sold_price'])
# # Y
# list(X)

In [8]:
additional_df.head()

,sold_price,sqarefootage,Type,Style,Bedrooms,Bathrooms,Kitchens,Rooms,Groceries #1 distance,Groceries #2 distance,...,Park #3 distance,Library #1 distance,Library #2 distance,Library #3 distance,Pharmacy #1 distance,Pharmacy #2 distance,Pharmacy #3 distance,Mall #1 distance,Mall #2 distance,Mall #3 distance
1,"526,800",500-599,Condo Apt,Apartment,1,1,1,4,0.44,0.6,...,1.31,1.21,1.26,1.26,0.14,0.39,1.17,1.22,1.46,2
0,"507,000",600-699,Condo Apt,Apartment,1,1,1,5,0.12,0.13,...,1.62,1.19,1.19,1.53,0.86,1.66,1.82,1.74,4.03,4.14
0,"465,000",800-899,Condo Apt,Apartment,2,2,1,5,1.32,2.01,...,1.65,0.78,0.83,2.15,2.48,2.07,2.32,2.36,3.04,3.22
0,"630,000",800-899,Condo Apt,Apartment,2,2,1,5,0.88,1.59,...,1.76,1.33,1.33,1.33,1.74,2.53,2.48,1.55,1.61,1.84
0,"682,000",500-599,Condo Apt,Multi-Level,1,1,1,5,0.28,0.38,...,0.61,0.58,1,1.25,0.38,0.96,1.29,0.36,0.78,1.27

In [9]:
len(X)

5317

In [10]:
X.infer_objects().dtypes

0
sqarefootage                object
Type                        object
Style                       object
Bedrooms                    object
Bathrooms                   object
Kitchens                    object
Rooms                       object
Groceries #1 distance       object
Groceries #2 distance       object
Groceries #3 distance       object
Restaurants #1 distance     object
Restaurants #2 distance     object
Restaurants #3 distance     object
Coffee #1 distance          object
Coffee #2 distance          object
Coffee #3 distance          object
Gas Station #1 distance     object
Gas Station #2 distance     object
Gas Station #3 distance     object
Medical Care #1 distance    object
Medical Care #2 distance    object
Medical Care #3 distance    object
Park #1 distance            object
Park #2 distance            object
Park #3 distance            object
Library #1 distance         object
Library #2 distance         object
Library #3 distance         object
Pharmacy #1 distance        object
Pharmacy #2 distance        object
Pharmacy #3 distance        object
Mall #1 distance            object
Mall #2 distance            object
Mall #3 distance            object
dtype: object

In [11]:
fields = [[ 'Bedrooms','Bathrooms','Kitchens', 'Rooms', 'Groceries #1 distance',
 'Groceries #2 distance',
 'Groceries #3 distance', 'Restaurants #1 distance',
 'Restaurants #2 distance',
 'Restaurants #3 distance','Coffee #1 distance',
 'Coffee #2 distance',
 'Coffee #3 distance','Gas Station #1 distance',
 'Gas Station #2 distance',
 'Gas Station #3 distance','Medical Care #1 distance',
 'Medical Care #2 distance',
 'Medical Care #3 distance','Park #1 distance',
 'Park #2 distance',
 'Park #3 distance','Library #1 distance',
 'Library #2 distance',
 'Library #3 distance','Pharmacy #1 distance',
 'Pharmacy #2 distance',
 'Pharmacy #3 distance','Mall #1 distance',
 'Mall #2 distance',
 'Mall #3 distance']]


for field in fields:
    X[field] = X[field].astype(str).astype(float)

In [12]:
X.infer_objects().dtypes

0
sqarefootage                 object
Type                         object
Style                        object
Bedrooms                    float64
Bathrooms                   float64
Kitchens                    float64
Rooms                       float64
Groceries #1 distance       float64
Groceries #2 distance       float64
Groceries #3 distance       float64
Restaurants #1 distance     float64
Restaurants #2 distance     float64
Restaurants #3 distance     float64
Coffee #1 distance          float64
Coffee #2 distance          float64
Coffee #3 distance          float64
Gas Station #1 distance     float64
Gas Station #2 distance     float64
Gas Station #3 distance     float64
Medical Care #1 distance    float64
Medical Care #2 distance    float64
Medical Care #3 distance    float64
Park #1 distance            float64
Park #2 distance            float64
Park #3 distance            float64
Library #1 distance         float64
Library #2 distance         float64
Library #3 distance         float64
Pharmacy #1 distance        float64
Pharmacy #2 distance        float64
Pharmacy #3 distance        float64
Mall #1 distance            float64
Mall #2 distance            float64
Mall #3 distance            float64
dtype: object

In [13]:
from sklearn.preprocessing import LabelEncoder,StandardScaler

d={}

print(len(X.columns))

for i in range(len(X.columns)):
    #if column is categorical
    if type(X.iloc[0,i])==str:
        print("categorical")
        print(X.iloc[0,i])

        le = LabelEncoder()
        X[X.columns[i]] = le.fit_transform(X[X.columns[i]])
        
        print(le.classes_)
        
        print(X[X.columns[i]])
        series = X[X.columns[i]]
        
        d[series.name] = {}
        
        le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
        
        d[series.name] = le_name_mapping

34
categorical
500-599
['0-499' '1' '1000-1199' '1100-1299' '1100-1500' '1200-1399' '1400-1599'
 '1500-2000' '1600-1799' '1800-1999' '2000-2249' '2000-2500' '2250-2499'
 '2500-2749' '2500-3000' '2750-2999' '3000-3249' '3000-3500' '3500-5000'
 '500-599' '5000+' '600-699' '700-1100' '700-799' '700-899' '800-899' '9'
 '900-1099' '900-999' '< 700']
1    19
0    21
0    25
0    25
0    19
     ..
0    22
0    28
0     5
0    28
0    23
Name: sqarefootage, Length: 5317, dtype: int64
categorical
Condo Apt
['Att/Row/Twnhouse' 'Co-Op Apt' 'Co-Ownership Apt' 'Comm Element Condo'
 'Condo Apt' 'Condo Townhouse' 'Det Condo' 'Detached' 'Duplex' 'Link'
 'Multiplex' 'Other' 'Semi-Det Condo' 'Semi-Detached' 'Store W/Apt/Offc'
 'Triplex']
1    4
0    4
0    4
0    4
0    4
    ..
0    7
0    4
0    5
0    5
0    4
Name: Type, Length: 5317, dtype: int64
categorical
Apartment
['1' '1 1/2 Storey' '2 1/2 Storey' '2-Storey' '3' '3-Storey' 'Apartment'
 'Bachelor/Studio' 'Backsplit 3' 'Backsplit 4' 'Backsplit 5' 'Bungaloft'
 'Bungalow' 'Bungalow-Raised' 'Loft' 'Multi-Level' 'Other' 'Sidesplit 3'
 'Sidesplit 4' 'Sidesplit 5' 'Stacked Townhse']
1     6
0     6
0     6
0     6
0    15
     ..
0    12
0     6
0     3
0     6
0     6
Name: Style, Length: 5317, dtype: int64

In [14]:
Y['sold_price'] = Y['sold_price'].str.replace(',', '').astype(float)


yScaler = StandardScaler()
yScaler.fit(Y)
Y = yScaler.transform(Y)

In [15]:
from sklearn.model_selection import train_test_split

Xtr,Xts,Ytr,Yts = train_test_split(X,Y,test_size=0.2, random_state=42)

In [16]:
from tensorflow import keras
import keras_tuner as kt
import tensorflow as tf
from keras_tuner import Hyperband,RandomSearch
import keras_tuner
from tensorflow.keras import layers
import numpy as np

from tensorflow.keras.callbacks import EarlyStopping

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=[Xtr.shape[1]]),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10),
  tf.keras.layers.Dense(1)
])

model.compile(optimizer='adam',
              loss=tf.keras.losses.mean_squared_error,
              metrics=['mean_squared_error'])



train_x = np.asarray(Xtr)
train_y = np.asarray(Ytr)
# validation_x = np.asarray(Xts)
# validation_y = np.asarray(Yts)


# model.fit(train_x, train_y, epochs=500)

2021-12-08 12:52:30.574974: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-12-08 12:52:30.575310: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [17]:

callback = EarlyStopping(monitor='val_mean_absolute_error', patience=10, verbose=1)



# Creating custom R^2 performance metric for keras models
def r2(y_true,y_pred):
    from keras import backend as K
    SS_res = K.sum(K.square(y_true-y_pred))
    SS_tot = K.sum(K.square(y_true - K.mean(y_true)))
    return (1 - SS_res/(SS_tot + K.epsilon()))

def model_builder(hp):
    model = keras.Sequential()
    model.add(keras.layers.Flatten(input_shape=[train_x.shape[1]]))
    for i in range(hp.Int("num_layers", 2, 10)): #number of layers
        model.add(
            layers.Dense(
                units=hp.Int("units_" + str(i), min_value=32, max_value=512, step=32), #number of units
                activation="relu",
            )
        )
    model.add(keras.layers.Dense(1))
    hp_learning_rate = hp.Choice('learning_rate', values=[1e-2, 1e-3, 1e-4])
    model.compile(
        optimizer=keras.optimizers.Adam(hp.Choice("learning_rate", [1e-2, 1e-3, 1e-4])),
                loss=keras.losses.mean_absolute_error,
              metrics=['mean_squared_error',r2,keras.losses.mean_absolute_error])
    return model

In [18]:
tuner = kt.Hyperband(model_builder,
                     objective=keras_tuner.Objective("val_r2", direction="max"),
                     max_epochs=1000,
                     executions_per_trial=1,
                     overwrite=True,
                     directory="my_dir",
                     project_name="KerasRegressor",
                    
)

In [20]:


tuner.search(train_x, train_y, epochs=1000, validation_split=0.2,callbacks=[callback])

Trial 2075 Complete [00h 00m 24s]
val_r2: 0.7465073466300964

Best val_r2 So Far: 0.8407493233680725
Total elapsed time: 05h 03m 40s
INFO:tensorflow:Oracle triggered exit

In [21]:
bestHparams=tuner.get_best_hyperparameters(num_trials=1)[0]

models_hyper = tuner.get_best_models(num_models=2)
best_model = models_hyper[0]
score = best_model.evaluate(Xts, Yts, verbose=0)

In [22]:
model = tuner.hypermodel.build(bestHparams)
model.fit(X, Y, epochs=50, validation_split=0.2)

model.save("./models/amenity_model")


# def f1(y_true, y_pred):
#     return 1

# model = tf.keras.models.load_model(path_to_model, custom_objects={'r2':r2})

Epoch 1/50
133/133 [==============================] - 1s 5ms/step - loss: 0.4266 - mean_squared_error: 0.5401 - r2: 0.3896 - mean_absolute_error: 0.4266 - val_loss: 0.2811 - val_mean_squared_error: 0.2877 - val_r2: 0.6336 - val_mean_absolute_error: 0.2811
Epoch 2/50
133/133 [==============================] - 1s 4ms/step - loss: 0.2741 - mean_squared_error: 0.2268 - r2: 0.7293 - mean_absolute_error: 0.2741 - val_loss: 0.2762 - val_mean_squared_error: 0.3037 - val_r2: 0.6448 - val_mean_absolute_error: 0.2762
Epoch 3/50
133/133 [==============================] - 1s 4ms/step - loss: 0.2533 - mean_squared_error: 0.2199 - r2: 0.7445 - mean_absolute_error: 0.2533 - val_loss: 0.2603 - val_mean_squared_error: 0.2276 - val_r2: 0.6409 - val_mean_absolute_error: 0.2603
Epoch 4/50
133/133 [==============================] - 1s 4ms/step - loss: 0.2555 - mean_squared_error: 0.2160 - r2: 0.7306 - mean_absolute_error: 0.2555 - val_loss: 0.2491 - val_mean_squared_error: 0.2589 - val_r2: 0.6927 - val_mean_absolute_error: 0.2491
Epoch 5/50
133/133 [==============================] - 1s 4ms/step - loss: 0.2387 - mean_squared_error: 0.1944 - r2: 0.7567 - mean_absolute_error: 0.2387 - val_loss: 0.2494 - val_mean_squared_error: 0.2437 - val_r2: 0.7009 - val_mean_absolute_error: 0.2494
Epoch 6/50
133/133 [==============================] - 1s 4ms/step - loss: 0.2425 - mean_squared_error: 0.1963 - r2: 0.7809 - mean_absolute_error: 0.2425 - val_loss: 0.2545 - val_mean_squared_error: 0.2789 - val_r2: 0.7100 - val_mean_absolute_error: 0.2545
Epoch 7/50
133/133 [==============================] - 1s 5ms/step - loss: 0.2212 - mean_squared_error: 0.1835 - r2: 0.7961 - mean_absolute_error: 0.2212 - val_loss: 0.2432 - val_mean_squared_error: 0.2067 - val_r2: 0.6545 - val_mean_absolute_error: 0.2432
Epoch 8/50
133/133 [==============================] - 1s 4ms/step - loss: 0.2220 - mean_squared_error: 0.2059 - r2: 0.7870 - mean_absolute_error: 0.2220 - val_loss: 0.2240 - val_mean_squared_error: 0.2085 - val_r2: 0.7523 - val_mean_absolute_error: 0.2240
Epoch 9/50
133/133 [==============================] - 1s 4ms/step - loss: 0.2145 - mean_squared_error: 0.1677 - r2: 0.8206 - mean_absolute_error: 0.2145 - val_loss: 0.2485 - val_mean_squared_error: 0.2950 - val_r2: 0.7084 - val_mean_absolute_error: 0.2485
Epoch 10/50
133/133 [==============================] - 1s 4ms/step - loss: 0.2046 - mean_squared_error: 0.1776 - r2: 0.8114 - mean_absolute_error: 0.2046 - val_loss: 0.2212 - val_mean_squared_error: 0.1836 - val_r2: 0.7445 - val_mean_absolute_error: 0.2212
Epoch 11/50
133/133 [==============================] - 1s 5ms/step - loss: 0.1966 - mean_squared_error: 0.1431 - r2: 0.8231 - mean_absolute_error: 0.1966 - val_loss: 0.2243 - val_mean_squared_error: 0.1908 - val_r2: 0.7303 - val_mean_absolute_error: 0.2243
Epoch 12/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1987 - mean_squared_error: 0.1428 - r2: 0.8311 - mean_absolute_error: 0.1987 - val_loss: 0.2268 - val_mean_squared_error: 0.1824 - val_r2: 0.7065 - val_mean_absolute_error: 0.2268
Epoch 13/50
133/133 [==============================] - 1s 4ms/step - loss: 0.2278 - mean_squared_error: 0.1863 - r2: 0.7200 - mean_absolute_error: 0.2278 - val_loss: 0.2243 - val_mean_squared_error: 0.2086 - val_r2: 0.6857 - val_mean_absolute_error: 0.2243
Epoch 14/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1821 - mean_squared_error: 0.1370 - r2: 0.8459 - mean_absolute_error: 0.1821 - val_loss: 0.2533 - val_mean_squared_error: 0.2726 - val_r2: 0.7166 - val_mean_absolute_error: 0.2533
Epoch 15/50
133/133 [==============================] - 1s 5ms/step - loss: 0.1925 - mean_squared_error: 0.1396 - r2: 0.8549 - mean_absolute_error: 0.1925 - val_loss: 0.2229 - val_mean_squared_error: 0.2402 - val_r2: 0.7614 - val_mean_absolute_error: 0.2229
Epoch 16/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1836 - mean_squared_error: 0.1271 - r2: 0.8412 - mean_absolute_error: 0.1836 - val_loss: 0.2110 - val_mean_squared_error: 0.1933 - val_r2: 0.7695 - val_mean_absolute_error: 0.2110
Epoch 17/50
133/133 [==============================] - 1s 5ms/step - loss: 0.1820 - mean_squared_error: 0.1323 - r2: 0.8530 - mean_absolute_error: 0.1820 - val_loss: 0.2164 - val_mean_squared_error: 0.1871 - val_r2: 0.7565 - val_mean_absolute_error: 0.2164
Epoch 18/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1748 - mean_squared_error: 0.1191 - r2: 0.8570 - mean_absolute_error: 0.1748 - val_loss: 0.2029 - val_mean_squared_error: 0.1780 - val_r2: 0.7581 - val_mean_absolute_error: 0.2029
Epoch 19/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1783 - mean_squared_error: 0.1205 - r2: 0.8502 - mean_absolute_error: 0.1783 - val_loss: 0.2235 - val_mean_squared_error: 0.2328 - val_r2: 0.7576 - val_mean_absolute_error: 0.2235
Epoch 20/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1962 - mean_squared_error: 0.1632 - r2: 0.8161 - mean_absolute_error: 0.1962 - val_loss: 0.2069 - val_mean_squared_error: 0.1900 - val_r2: 0.7678 - val_mean_absolute_error: 0.2069
Epoch 21/50
133/133 [==============================] - 1s 5ms/step - loss: 0.1743 - mean_squared_error: 0.1363 - r2: 0.8638 - mean_absolute_error: 0.1743 - val_loss: 0.2043 - val_mean_squared_error: 0.1849 - val_r2: 0.7634 - val_mean_absolute_error: 0.2043
Epoch 22/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1729 - mean_squared_error: 0.1184 - r2: 0.8503 - mean_absolute_error: 0.1729 - val_loss: 0.2094 - val_mean_squared_error: 0.1804 - val_r2: 0.7565 - val_mean_absolute_error: 0.2094
Epoch 23/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1734 - mean_squared_error: 0.1261 - r2: 0.8420 - mean_absolute_error: 0.1734 - val_loss: 0.2028 - val_mean_squared_error: 0.1772 - val_r2: 0.7640 - val_mean_absolute_error: 0.2028
Epoch 24/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1838 - mean_squared_error: 0.1534 - r2: 0.8567 - mean_absolute_error: 0.1838 - val_loss: 0.2407 - val_mean_squared_error: 0.3138 - val_r2: 0.6919 - val_mean_absolute_error: 0.2407
Epoch 25/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1661 - mean_squared_error: 0.1145 - r2: 0.8558 - mean_absolute_error: 0.1661 - val_loss: 0.2011 - val_mean_squared_error: 0.1826 - val_r2: 0.7781 - val_mean_absolute_error: 0.2011
Epoch 26/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1696 - mean_squared_error: 0.1245 - r2: 0.8634 - mean_absolute_error: 0.1696 - val_loss: 0.1959 - val_mean_squared_error: 0.1596 - val_r2: 0.7852 - val_mean_absolute_error: 0.1959
Epoch 27/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1657 - mean_squared_error: 0.1070 - r2: 0.8841 - mean_absolute_error: 0.1657 - val_loss: 0.2079 - val_mean_squared_error: 0.1856 - val_r2: 0.7634 - val_mean_absolute_error: 0.2079
Epoch 28/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1707 - mean_squared_error: 0.1357 - r2: 0.8638 - mean_absolute_error: 0.1707 - val_loss: 0.2028 - val_mean_squared_error: 0.1926 - val_r2: 0.7684 - val_mean_absolute_error: 0.2028
Epoch 29/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1585 - mean_squared_error: 0.1123 - r2: 0.8757 - mean_absolute_error: 0.1585 - val_loss: 0.1980 - val_mean_squared_error: 0.1600 - val_r2: 0.7661 - val_mean_absolute_error: 0.1980
Epoch 30/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1732 - mean_squared_error: 0.1252 - r2: 0.8619 - mean_absolute_error: 0.1732 - val_loss: 0.1933 - val_mean_squared_error: 0.1734 - val_r2: 0.7838 - val_mean_absolute_error: 0.1933
Epoch 31/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1493 - mean_squared_error: 0.0930 - r2: 0.8901 - mean_absolute_error: 0.1493 - val_loss: 0.2123 - val_mean_squared_error: 0.1712 - val_r2: 0.7456 - val_mean_absolute_error: 0.2123
Epoch 32/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1668 - mean_squared_error: 0.1289 - r2: 0.8718 - mean_absolute_error: 0.1668 - val_loss: 0.2023 - val_mean_squared_error: 0.1747 - val_r2: 0.7889 - val_mean_absolute_error: 0.2023

Epoch 33/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1584 - mean_squared_error: 0.0983 - r2: 0.8768 - mean_absolute_error: 0.1584 - val_loss: 0.1996 - val_mean_squared_error: 0.1835 - val_r2: 0.7761 - val_mean_absolute_error: 0.1996
Epoch 34/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1518 - mean_squared_error: 0.1065 - r2: 0.8841 - mean_absolute_error: 0.1518 - val_loss: 0.1947 - val_mean_squared_error: 0.1758 - val_r2: 0.7685 - val_mean_absolute_error: 0.1947
Epoch 35/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1619 - mean_squared_error: 0.1105 - r2: 0.8869 - mean_absolute_error: 0.1619 - val_loss: 0.2031 - val_mean_squared_error: 0.1912 - val_r2: 0.7677 - val_mean_absolute_error: 0.2031
Epoch 36/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1510 - mean_squared_error: 0.0935 - r2: 0.8776 - mean_absolute_error: 0.1510 - val_loss: 0.1917 - val_mean_squared_error: 0.1539 - val_r2: 0.7897 - val_mean_absolute_error: 0.1917
Epoch 37/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1481 - mean_squared_error: 0.0941 - r2: 0.8938 - mean_absolute_error: 0.1481 - val_loss: 0.1890 - val_mean_squared_error: 0.1719 - val_r2: 0.7978 - val_mean_absolute_error: 0.1890
Epoch 38/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1467 - mean_squared_error: 0.1035 - r2: 0.8769 - mean_absolute_error: 0.1467 - val_loss: 0.1878 - val_mean_squared_error: 0.1611 - val_r2: 0.7887 - val_mean_absolute_error: 0.1878
Epoch 39/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1504 - mean_squared_error: 0.0923 - r2: 0.9032 - mean_absolute_error: 0.1504 - val_loss: 0.1896 - val_mean_squared_error: 0.1539 - val_r2: 0.7804 - val_mean_absolute_error: 0.1896
Epoch 40/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1458 - mean_squared_error: 0.0990 - r2: 0.8978 - mean_absolute_error: 0.1458 - val_loss: 0.2142 - val_mean_squared_error: 0.2428 - val_r2: 0.7567 - val_mean_absolute_error: 0.2142
Epoch 41/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1540 - mean_squared_error: 0.1085 - r2: 0.8930 - mean_absolute_error: 0.1540 - val_loss: 0.1987 - val_mean_squared_error: 0.1831 - val_r2: 0.7876 - val_mean_absolute_error: 0.1987
Epoch 42/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1558 - mean_squared_error: 0.1331 - r2: 0.8846 - mean_absolute_error: 0.1558 - val_loss: 0.1911 - val_mean_squared_error: 0.1681 - val_r2: 0.7984 - val_mean_absolute_error: 0.1911
Epoch 43/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1421 - mean_squared_error: 0.0909 - r2: 0.9065 - mean_absolute_error: 0.1421 - val_loss: 0.1939 - val_mean_squared_error: 0.1582 - val_r2: 0.7859 - val_mean_absolute_error: 0.1939
Epoch 44/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1533 - mean_squared_error: 0.1069 - r2: 0.8952 - mean_absolute_error: 0.1533 - val_loss: 0.1948 - val_mean_squared_error: 0.1420 - val_r2: 0.7968 - val_mean_absolute_error: 0.1948
Epoch 45/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1420 - mean_squared_error: 0.0909 - r2: 0.9056 - mean_absolute_error: 0.1420 - val_loss: 0.1904 - val_mean_squared_error: 0.1632 - val_r2: 0.8028 - val_mean_absolute_error: 0.1904
Epoch 46/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1393 - mean_squared_error: 0.0839 - r2: 0.8986 - mean_absolute_error: 0.1393 - val_loss: 0.1915 - val_mean_squared_error: 0.1577 - val_r2: 0.7922 - val_mean_absolute_error: 0.1915
Epoch 47/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1413 - mean_squared_error: 0.0906 - r2: 0.9143 - mean_absolute_error: 0.1413 - val_loss: 0.1971 - val_mean_squared_error: 0.1687 - val_r2: 0.7753 - val_mean_absolute_error: 0.1971
Epoch 48/50
133/133 [==============================] - 1s 5ms/step - loss: 0.1413 - mean_squared_error: 0.0731 - r2: 0.9088 - mean_absolute_error: 0.1413 - val_loss: 0.1970 - val_mean_squared_error: 0.1556 - val_r2: 0.7789 - val_mean_absolute_error: 0.1970
Epoch 49/50
133/133 [==============================] - 1s 5ms/step - loss: 0.1329 - mean_squared_error: 0.0735 - r2: 0.9202 - mean_absolute_error: 0.1329 - val_loss: 0.2086 - val_mean_squared_error: 0.2070 - val_r2: 0.7763 - val_mean_absolute_error: 0.2086
Epoch 50/50
133/133 [==============================] - 1s 4ms/step - loss: 0.1324 - mean_squared_error: 0.0803 - r2: 0.9183 - mean_absolute_error: 0.1324 - val_loss: 0.1880 - val_mean_squared_error: 0.1449 - val_r2: 0.7730 - val_mean_absolute_error: 0.1880

2021-12-08 18:11:41.081757: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.

INFO:tensorflow:Assets written to: ./models/amenity_model/assets

In [24]:
load_model_from_file = tf.keras.models.load_model("./models/amenity_model",custom_objects={'r2':r2})

In [53]:
validation_x = np.asarray(Xts)
validation_y = np.asarray(Yts)


absolute_errors =[]
i=0
for index, row in Xts.iterrows():

    test_input = row
    test_input = test_input.values.reshape(1,34) 
    
    result = load_model_from_file.predict(test_input)
    predicted = yScaler.inverse_transform(result)
    
    actual = yScaler.inverse_transform(np.array(Yts[i]))
    
    
    
    actual = int(actual)
    predicted = int(predicted)
    
    
    absolute_error = (abs(actual-predicted))/actual
        
        
    absolute_errors.append(absolute_error)

    i = i + 1 
    
    

def Average(lst):
    return sum(lst) / len(lst)
  

average = Average(absolute_errors)


average = average * 100
# Printing average of the list
print("Average of the list =", round(average, 2), "%")

Average of the list = 9.65 %